SUPABASE_URL = "https://qanworhvskscqcwbqnqx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhbndvcmh2c2tzY3Fjd2JxbnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzI1MDYsImV4cCI6MjA3MTIwODUwNn0.3OJLnb1l1ag6HG8dTw6rsigsrulgSkmIUA7yaknj740"
